"""What to change, and what changing it would actually do.

`feedback_for_agent` reports consequences and never corrections, because for a
benchmarked agent, working out the fix IS the thing being measured. That rule
does not apply to a person: you withhold the answer from a subject under test,
not from a colleague who asked for help.

So this module says "narrow to two arms and use six wells each" - and then,
inseparably, what that does to the numbers. **Every suggestion carries its own
simulated consequence**, because a suggestion without one is just an opinion,
and an opinion is what this project refuses to produce.

Where the suggestions come from matters more than the suggestions. They are NOT
generated by asking a model what a good experiment looks like. Each is a
one-lever perturbation of the design the user actually proposed, scored by the
same twin that scored the original. The advisor cannot recommend anything it
has not simulated, and it reports the delta rather than a verdict.

Three properties that keep it honest:

**It can say nothing helps.** For Experiment 4 no single change reaches power,
and that is the finding rather than a failure of the search. An advisor that
always produces an encouraging next step is an advisor that will encourage you
into a doomed plate.

**It respects the apparatus.** Suggestions never exceed the calibrated capacity.
An early scorer bug pushed an agent into 288 wells across 24 plates by naming a
requirement without naming the limit; the same mistake made here would send a
researcher to spend money on it.

**It flags what rests on an assumption.** A search over designs IS a search
against the twin (PLAN 9.1), so any suggestion whose benefit does not survive
the plausible range of an ASSUMED constant is marked. Aprotinin is the live case:
recommending it is recommending a number nobody measured.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from .calibration import DEFAULT_PARAMS, PLATE_WELLS, TwinParams
from .design import DesignSpec, OutOfTwinScopeError
from .score import HEADLINE_CONTRAST, DesignScore, score_design

# Endpoints worth trying, in hours since cast. Chosen to straddle the observed
# fibrinolytic window rather than to be round numbers: the scaffold survival
# scale is ~184 h for contractile arms, so the interesting question is what
# happens either side of that.
CANDIDATE_ENDPOINTS = (72.0, 96.0, 120.0, 144.0, 168.0, 240.0)

# An early frame is what makes the contraction curve identifiable at all;
# Experiment 4's first imageable point was 24 h, by which it was ~94% over.
EARLY_TIMEPOINTS = (2.0, 6.0, 12.0)

# How many levers may be stacked. Bounded so the combined design remains a short,
# readable chain of simulated steps rather than the output of an unbounded search
# against the twin (PLAN 9.1).
MAX_COMBINE_ROUNDS = 5


@dataclass
class Suggestion:
    """One change, and what the twin says it would do."""

    lever: str
    change: str                  # what to do at the bench
    before: DesignScore
    after: DesignScore
    caveat: str = ""
    assumption_sensitive: bool = False

    @property
    def delta_power(self) -> float:
        return self.after.power - self.before.power

    @property
    def delta_testable(self) -> float:
        return self.after.testable_rate - self.before.testable_rate

    @property
    def helps(self) -> bool:
        """Improves the chance of a testable result or of recovering the effect.

        Testability is included deliberately: a change that takes a plate from
        yielding nothing to yielding data is progress even when power stays low,
        and it is usually the change that has to come first.
        """
        return self.delta_power > 0.01 or self.delta_testable > 0.05

    def line(self) -> str:
        arrow = (
            f"power {self.before.power:.0%} -> {self.after.power:.0%}"
            f"   testable {self.before.testable_rate:.0%} -> "
            f"{self.after.testable_rate:.0%}"
        )
        if self.before.mean_lysed_fraction - self.after.mean_lysed_fraction > 0.05:
            arrow += (
                f"   lysed {self.before.mean_lysed_fraction:.0%} -> "
                f"{self.after.mean_lysed_fraction:.0%}"
            )
        out = [f"{self.change}", f"    {arrow}"]
        if self.assumption_sensitive:
            out.append(
                "    ⚠ rests on an ASSUMED constant - aprotinin's effect was "
                "never measured here"
            )
        if self.caveat:
            out.append(f"    {self.caveat}")
        return "\n".join(out)


@dataclass
class Advice:
    """Every change tried, whether or not it helped."""

    original: DesignScore
    suggestions: list[Suggestion] = field(default_factory=list)
    best_combined: tuple[DesignSpec, DesignScore] | None = None
    # The order the levers were applied in, so the final design traces back to a
    # chain of individually-simulated steps rather than appearing from a search.
    combination_order: list[str] = field(default_factory=list)

    @property
    def helpful(self) -> list[Suggestion]:
        return sorted(
            (s for s in self.suggestions if s.helps),
            key=lambda s: (s.delta_power, s.delta_testable),
            reverse=True,
        )

    def summary(self, target_power: float = 0.8) -> str:
        lines: list[str] = []
        if self.original.declined:
            return (
                "This design declines to run the experiment, so there is nothing "
                "to improve.\nWhether declining was right is answered by `refute "
                "baselines`."
            )

        lines.append(
            f"starting point: power {self.original.power:.0%}, testable "
            f"{self.original.testable_rate:.0%}, "
            f"{self.original.mean_lysed_fraction:.0%} of wells lost"
        )
        lines.append("")

        helpful = self.helpful
        if not helpful:
            lines.append("No single change to this design improves it.")
        else:
            lines.append(f"{len(helpful)} change(s) help, best first:")
            lines.append("")
            for i, s in enumerate(helpful, 1):
                lines.append(f"  {i}. {s.line()}")
                lines.append("")

        tried = len(self.suggestions)
        useless = tried - len(helpful)
        if useless:
            lines.append(
                f"({useless} of {tried} changes tried made no difference or made "
                "it worse - listed with --all)"
            )
            lines.append("")

        if self.best_combined is not None:
            spec, score = self.best_combined
            lines.append("EVERYTHING AT ONCE")
            if self.combination_order:
                lines.append(
                    f"  applied in order: {' -> '.join(self.combination_order)}"
                )
            lines.append(
                f"  {len(spec.conditions)} arms x {spec.replicates_per_condition} "
                f"wells, endpoint {spec.endpoint_time_h:.0f} h"
                f"{', antifibrinolytic' if spec.antifibrinolytic else ''}"
            )
            lines.append(
                f"  power {score.power:.0%}   testable {score.testable_rate:.0%}"
                f"   lysed {score.mean_lysed_fraction:.0%}"
            )
            if score.power < target_power:
                need = (
                    f"~{score.replicates_needed} wells per arm"
                    if score.replicates_needed > 0
                    else "an unestimable number of wells"
                )
                lines.append("")
                lines.append(
                    f"  Even applying every improvement, this reaches "
                    f"{score.power:.0%}, not {target_power:.0%}.\n"
                    f"  It needs {need}, and the apparatus holds "
                    f"{PLATE_WELLS}.\n\n"
                    "  That is not a failure of the search. The honest conclusion "
                    "is that the\n  question cannot be answered at this scale - "
                    "which is a legitimate\n  result, and the one this benchmark "
                    "was built to demonstrate."
                )
        return "\n".join(lines)


def _score(design: DesignSpec, params: TwinParams, n_sims: int, seed: int | None):
    return score_design(design, params=params, n_sims=n_sims, seed=seed)


def _variants(design: DesignSpec) -> list[tuple[str, str, DesignSpec, str]]:
    """(lever, human description, variant, caveat) - one lever changed each."""
    out: list[tuple[str, str, DesignSpec, str]] = []

    # --- protect the scaffold -------------------------------------------
    if not design.antifibrinolytic:
        out.append((
            "antifibrinolytic",
            "Add an antifibrinolytic to the gel formulation",
            design.model_copy(update={
                "antifibrinolytic": True, "anticipates_scaffold_failure": True,
            }),
            "",
        ))

    # --- finish before the scaffold fails -------------------------------
    for endpoint in CANDIDATE_ENDPOINTS:
        if endpoint <= design.treatment_time_h or endpoint >= design.endpoint_time_h:
            continue
        times = sorted(set(t for t in design.imaging_times_h if t <= endpoint) | {endpoint})
        out.append((
            "endpoint",
            f"Move the endpoint from {design.endpoint_time_h:.0f} h to "
            f"{endpoint:.0f} h",
            design.model_copy(update={
                "endpoint_time_h": endpoint, "imaging_times_h": times,
            }),
            "Ends the experiment earlier - check the treatment has had time to act.",
        ))

    # --- spend the plate on the comparison that matters -----------------
    a, b = HEADLINE_CONTRAST
    if len(design.conditions) > 2 and set(design.conditions) >= {a, b}:
        reps = PLATE_WELLS // 2
        out.append((
            "narrow",
            f"Drop to the two arms that answer the question ({a} vs {b}) and "
            f"put {reps} wells in each",
            design.model_copy(update={
                "conditions": [a, b], "replicates_per_condition": reps,
            }),
            "You lose the other comparisons. They were not what the question asked.",
        ))

    # --- more replicates, within the apparatus --------------------------
    arms = max(len(design.conditions), 1)
    room = PLATE_WELLS // arms
    if room > design.replicates_per_condition:
        out.append((
            "replicates",
            f"Fill the plate: {room} wells per arm instead of "
            f"{design.replicates_per_condition}",
            design.model_copy(update={"replicates_per_condition": room}),
            "",
        ))

    # --- make the measurement usable ------------------------------------
    if not design.normalise_to_own_baseline:
        out.append((
            "normalise",
            "Normalise each well to its own pre-treatment image, not to a group "
            "mean",
            design.model_copy(update={"normalise_to_own_baseline": True}),
            "Costs nothing at the bench - it is an analysis choice.",
        ))

    if not design.locked_imaging_protocol:
        out.append((
            "imaging",
            "Fix the imaging setup: one well at a time, constant geometry and "
            "lighting, a scale in frame",
            design.model_copy(update={"locked_imaging_protocol": True}),
            "Costs nothing but discipline.",
        ))

    # --- a pre-treatment baseline, if there is not one ------------------
    if not any(t <= design.treatment_time_h for t in design.imaging_times_h):
        times = sorted(set(design.imaging_times_h) | {design.treatment_time_h})
        out.append((
            "baseline",
            f"Image at {design.treatment_time_h:.0f} h, before treating, so each "
            "well has its own reference",
            design.model_copy(update={"imaging_times_h": times}),
            "",
        ))

    # --- catch the fast phase -------------------------------------------
    if not any(t <= 12 for t in design.imaging_times_h):
        times = sorted(set(design.imaging_times_h) | set(EARLY_TIMEPOINTS))
        out.append((
            "early-imaging",
            "Add early frames (2, 6, 12 h) so the contraction curve is "
            "identifiable",
            design.model_copy(update={"imaging_times_h": times}),
            "Will not change power - it changes what you can conclude about "
            "kinetics.",
        ))

    return out


def advise(
    design: DesignSpec,
    params: TwinParams = DEFAULT_PARAMS,
    n_sims: int = 400,
    seed: int | None = 0,
) -> Advice:
    """Try one change at a time, then all the helpful ones together."""
    base = _score(design, params, n_sims, seed)
    result = Advice(original=base)
    if base.declined:
        return result

    for lever, change, variant, caveat in _variants(design):
        try:
            after = _score(variant, params, n_sims, seed)
        except OutOfTwinScopeError:
            continue
        result.suggestions.append(
            Suggestion(
                lever=lever,
                change=change,
                before=base,
                after=after,
                caveat=caveat,
                # A suggestion whose benefit does not survive the plausible range
                # of an uncalibrated constant is a suggestion about that constant.
                assumption_sensitive=after.verdict_sensitive_to_assumption,
            )
        )

    # Combine greedily, RE-SCORING after each step rather than applying whatever
    # helped in isolation.
    #
    # This is not fussiness. Applying only the individually-helpful levers
    # produced a worse plate than a competent human writes, because the levers
    # interact: narrowing to the two arms that matter does nothing on its own -
    # both surviving arms are the most contractile ones, so both still dissolve -
    # and becomes the single biggest gain once the scaffold is protected. A
    # one-pass combiner never discovers that, and an advisor that recommends
    # worse than a person would is worse than no advisor.
    #
    # Bounded and recorded: each step is the best available improvement at that
    # point, and the sequence is kept so the final design stays attributable to
    # a chain of individually-simulated changes rather than to a search. PLAN 9.1
    # is the reason for the bound - a search over designs is a search against the
    # twin.
    combined = design
    combined_score = base
    for _round in range(MAX_COMBINE_ROUNDS):
        best: tuple[float, float, DesignSpec, DesignScore, str] | None = None
        for lever, _change, variant, _caveat in _variants(combined):
            try:
                cand = _score(variant, params, n_sims, seed)
            except OutOfTwinScopeError:
                continue
            gain = cand.power - combined_score.power
            testable_gain = cand.testable_rate - combined_score.testable_rate
            if gain <= 0.005 and testable_gain <= 0.02:
                continue
            key = (gain, testable_gain)
            if best is None or key > (best[0], best[1]):
                best = (gain, testable_gain, variant, cand, lever)
        if best is None:
            break
        _g, _t, combined, combined_score, lever = best
        result.combination_order.append(lever)

    if combined != design:
        result.best_combined = (combined, combined_score)
    return result
