/* Tier-0 power arithmetic, in the browser.
 *
 * This is a SECOND implementation of refute/tier0.py, which is a liability: two
 * copies of the same maths drift, and the drift is silent. It exists because the
 * form must work with no server and no API key - nothing a lab member types
 * leaves their machine.
 *
 * The liability is managed rather than accepted. `scripts/build_site.py` runs a
 * dense grid through BOTH implementations at build time and refuses to build if
 * they disagree beyond 1e-6. If you edit either file, the build tells you.
 *
 * Noncentral t is used rather than the normal approximation on purpose: at the
 * n=3 to n=12 sizes a bench experiment actually runs, the normal approximation
 * overstates power, and overstating power is the error this whole project exists
 * to complain about.
 *
 * The critical values come from a table generated by scipy at build time
 * (T_CRIT below, injected). n is an integer, so df = 2n-2 is discrete and a
 * table is exact - which avoids implementing an inverse t distribution here.
 */

'use strict';

// --- injected at build time from scipy -------------------------------------
// T_CRIT[alpha][df]        = t.ppf(1 - alpha/2, df)   two-sided critical value
// T_POWER[targetPower][df] = t.ppf(targetPower, df)   one-sided, for the MDE
/* __T_CRIT__ */

const MIN_REPLICATES = 2;
// Bounded by the injected critical-value table. Past a few hundred per arm the
// answer is "not at this scale" whatever the exact number, and reporting 8,412
// would imply a precision the user's own SD estimate cannot support.
const MAX_SEARCH_REPLICATES = 400;

function lgamma(x) {
  // Lanczos approximation, g=7, n=9. Accurate to ~1e-13 for x > 0.
  const g = [
    0.99999999999980993, 676.5203681218851, -1259.1392167224028,
    771.32342877765313, -176.61502916214059, 12.507343278686905,
    -0.13857109526572012, 9.9843695780195716e-6, 1.5056327351493116e-7,
  ];
  if (x < 0.5) {
    // Reflection: Gamma(x)Gamma(1-x) = pi / sin(pi x)
    return Math.log(Math.PI / Math.sin(Math.PI * x)) - lgamma(1 - x);
  }
  x -= 1;
  let a = g[0];
  const t = x + 7.5;
  for (let i = 1; i < 9; i++) a += g[i] / (x + i);
  return 0.5 * Math.log(2 * Math.PI) + (x + 0.5) * Math.log(t) - t + Math.log(a);
}

function normCdf(z) {
  // Abramowitz & Stegun 26.2.17 via erf; |error| < 1.5e-7, which is well inside
  // the tolerance the build-time check enforces.
  const sign = z < 0 ? -1 : 1;
  const x = Math.abs(z) / Math.SQRT2;
  const t = 1 / (1 + 0.3275911 * x);
  const y =
    1 -
    ((((1.061405429 * t - 1.453152027) * t + 1.421413741) * t - 0.284496736) * t +
      0.254829592) *
      t *
      Math.exp(-x * x);
  return 0.5 * (1 + sign * y);
}

function chi2LogPdf(v, df) {
  const k = df / 2;
  return (k - 1) * Math.log(v) - v / 2 - k * Math.LN2 - lgamma(k);
}

/* Noncentral t tail probabilities by integrating over the chi-square mixing
 * variable:  T = (Z + delta) / sqrt(V/df),  V ~ chi2(df)
 *
 *   P(T > t)  = INT Phi(delta - t*sqrt(v/df)) f(v) dv
 *   P(T <= t) = INT Phi(t*sqrt(v/df) - delta) f(v) dv
 *
 * Substituted u = sqrt(v/df), so v = df*u^2 and dv = 2*df*u du. That is not
 * cosmetic: integrating in v leaves sqrt(v) in the integrand, whose derivatives
 * are unbounded at v=0, and Simpson's error bound requires them bounded. At
 * df=2 the chi-square density is non-zero at v=0 so the singularity is fully
 * exposed - it produced a 4.4e-4 disagreement with scipy, caught by the
 * build-time cross-check. In u the integrand is smooth and the same panel count
 * lands well inside 1e-9.
 *
 * The panel count is generous on purpose: this runs once per keystroke on one
 * core, so accuracy is cheaper than cleverness.
 */
function nctTails(t, df, delta) {
  // Cover the chi-square mass, then convert the bound to u.
  const vHi = df + 16 * Math.sqrt(2 * df) + 40;
  const uHi = Math.sqrt(vHi / df);
  const n = 2000; // even
  const h = uHi / n;

  let sfSum = 0;
  let cdfSum = 0;
  for (let i = 0; i <= n; i++) {
    const u = i * h;
    const w = i === 0 || i === n ? 1 : i % 2 === 1 ? 4 : 2;
    // Jacobian 2*df*u; at u=0 the whole term vanishes, so no singularity.
    const v = df * u * u;
    const jac = 2 * df * u;
    const dens = u === 0 ? 0 : Math.exp(chi2LogPdf(v, df)) * jac;
    const scaled = t * u;
    sfSum += w * dens * normCdf(delta - scaled);
    cdfSum += w * dens * normCdf(scaled - delta);
  }
  const f = h / 3;
  return { sf: sfSum * f, cdf: cdfSum * f };
}

function tCrit(df, alpha) {
  const key = String(alpha);
  const table = T_CRIT[key];
  if (!table) throw new Error('no critical values for alpha=' + alpha);
  const v = table[String(df)];
  if (v === undefined) throw new Error('no critical value for df=' + df);
  return v;
}

/** Power of a two-sided two-sample t-test. Mirrors tier0._power. */
function power(d, n, alpha) {
  if (n < MIN_REPLICATES) return 0;
  const df = 2 * n - 2;
  const ncp = d * Math.sqrt(n / 2);
  const crit = tCrit(df, alpha);
  const upper = nctTails(crit, df, ncp).sf;
  const lower = nctTails(-crit, df, ncp).cdf;
  return Math.min(1, upper + lower);
}

/** Replicates per arm needed to reach the target. -1 past the search bound. */
function replicatesNeeded(d, alpha, targetPower) {
  for (let n = MIN_REPLICATES; n <= MAX_SEARCH_REPLICATES; n++) {
    if (power(d, n, alpha) >= targetPower) return n;
  }
  return -1;
}

function tPower(df, targetPower) {
  // A SEPARATE table, not tCrit(df, 2*(1-targetPower)). Deriving the key by
  // arithmetic gave 2*(1-0.8) === 0.3999999999999999, which missed the "0.4"
  // entry and threw. Float arithmetic must never produce a lookup key.
  const table = T_POWER[String(targetPower)];
  if (!table) throw new Error('no quantiles for target power=' + targetPower);
  const v = table[String(df)];
  if (v === undefined) throw new Error('no quantile for df=' + df);
  return v;
}

/** Smallest detectable difference at the target power. Mirrors tier0. */
function minDetectableEffect(sd, n, alpha, targetPower) {
  if (n < MIN_REPLICATES) return Infinity;
  const df = 2 * n - 2;
  const z = tCrit(df, alpha) + tPower(df, targetPower);
  return z * sd * Math.sqrt(2 / n);
}

function assess(input) {
  const { effect, sd, arms, n, capacity, alpha, targetPower } = input;
  if (!(sd > 0)) throw new Error('variability must be positive');
  if (!effect) throw new Error('effect must be non-zero');
  if (arms < 2) throw new Error('a comparison needs at least 2 arms');

  const d = Math.abs(effect / sd);
  const p = power(d, n, alpha);
  const needed = replicatesNeeded(d, alpha, targetPower);
  const mde = minDetectableEffect(sd, n, alpha, targetPower);

  let feasibility;
  if (needed <= 0) feasibility = 'beyond-scale';
  else if (needed * arms > capacity) feasibility = 'infeasible';
  else feasibility = 'feasible';

  return {
    d, power: p, replicatesNeeded: needed, minDetectableEffect: mde,
    feasibility,
    totalUnits: arms * n,
    fitsCapacity: arms * n <= capacity,
    underpowered: p < targetPower,
  };
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { power, replicatesNeeded, minDetectableEffect, assess };
}
